### PR TITLE
Deletes Unused, Duplicate Files and Fixes Mistakes

### PR DESCRIPTION
**Pull request by Alexshreds**
@WarlordToby Rule number 1.2 of codenerds: compile...

__defines/defines -> code/defines
mob/dead -> mob/observer
game/objects -> game/obj

### CODE REVIEW

**Comment by Cherkir** [comment]
too much code to check so I'll just merge it and revert if anything stops working

**Comment by Cherkir** [comment]
nevermind conflicts

**Comment by Cherkir** [comment]
could you update CEV_Eris-1.dmm to the latest and see if it fixes?

**Comment by Alexshreds** [comment]
oh that's fucking nice
don't merge this chuckle fuckery

**Comment by Alexshreds** [comment]
Alright, that's better

**Comment by Alexshreds** [comment]
ALRIGHT, we are back in business

**Pull request merged**
